// Generated by tools/gen-brands.py from web/icons.js — do not edit by hand.
// Brand marks: Simple Icons (https://simpleicons.org, CC0-1.0). They identify
// third-party services; all trademarks belong to their respective owners.
import Foundation

/// Which brand a service is, by the same rules as the web client's
/// `brandSlug()`, so a container shows the same mark in both.
enum Brands {
    /// slug → brand colour. The mark itself is the asset `brand-<slug>`.
    static let colors: [String: UInt32] = [
        "adguard": 0x68BC71,
        "alpinelinux": 0x0D597F,
        "anthropic": 0x191919,
        "authelia": 0x113155,
        "authentik": 0xFD4B2D,
        "caddy": 0x1F88C0,
        "clickhouse": 0xFFCC01,
        "cloudflare": 0xF38020,
        "coder": 0x000000,
        "debian": 0xA81D33,
        "docker": 0x2496ED,
        "duplicati": 0x1E3A8A,
        "eclipsemosquitto": 0x3C5280,
        "element": 0x0DBD8B,
        "gitea": 0x609926,
        "grafana": 0xF46800,
        "homeassistant": 0x18BCF2,
        "immich": 0x4250AF,
        "influxdb": 0x22ADF6,
        "jellyfin": 0x00A4DC,
        "letsencrypt": 0x003A70,
        "mariadb": 0x003545,
        "matrix": 0x000000,
        "meilisearch": 0xFF5CAA,
        "mongodb": 0x47A248,
        "mysql": 0x4479A1,
        "n8n": 0xEA4B71,
        "nextcloud": 0x0082C9,
        "nginx": 0x009639,
        "nginxproxymanager": 0xF15833,
        "nodedotjs": 0x5FA04E,
        "ntfy": 0x317F6F,
        "ollama": 0x000000,
        "onlyoffice": 0x444444,
        "openai": 0x412991,
        "paperlessngx": 0x17541F,
        "pihole": 0x96060C,
        "plex": 0xEBAF00,
        "portainer": 0x13BEF9,
        "postgresql": 0x4169E1,
        "prometheus": 0xE6522C,
        "python": 0x3776AB,
        "rabbitmq": 0xFF6600,
        "redis": 0xFF4438,
        "searxng": 0x3050FF,
        "syncthing": 0x0891D1,
        "tailscale": 0x242424,
        "traefikproxy": 0x24A1C1,
        "ubuntu": 0xE95420,
        "uptimekuma": 0x5CDD8B,
        "vaultwarden": 0x000000,
        "watchtower": 0x416271,
        "wireguard": 0x88171A,
    ]

    /// alias → slug, in the web client's order: the substring pass takes the
    /// first alias that fits, so the order is part of the behaviour.
    static let aliasList: [(String, String)] = [
        ("adguard", "adguard"),
        ("alpine", "alpinelinux"),
        ("alpinelinux", "alpinelinux"),
        ("anthropic", "anthropic"),
        ("authelia", "authelia"),
        ("authentik", "authentik"),
        ("bitwarden", "vaultwarden"),
        ("caddy", "caddy"),
        ("cadvisor", "prometheus"),
        ("certbot", "letsencrypt"),
        ("claude", "anthropic"),
        ("clickhouse", "clickhouse"),
        ("cloudflare", "cloudflare"),
        ("coder", "coder"),
        ("codeserver", "coder"),
        ("debian", "debian"),
        ("docker", "docker"),
        ("documentserver", "onlyoffice"),
        ("duplicati", "duplicati"),
        ("eclipsemosquitto", "eclipsemosquitto"),
        ("element", "element"),
        ("gitea", "gitea"),
        ("gpt", "openai"),
        ("grafana", "grafana"),
        ("homeassistant", "homeassistant"),
        ("immich", "immich"),
        ("influxdb", "influxdb"),
        ("jellyfin", "jellyfin"),
        ("letsencrypt", "letsencrypt"),
        ("loki", "grafana"),
        ("mariadb", "mariadb"),
        ("matrix", "matrix"),
        ("mautrix", "matrix"),
        ("meilisearch", "meilisearch"),
        ("mongo", "mongodb"),
        ("mongodb", "mongodb"),
        ("mosquitto", "eclipsemosquitto"),
        ("mqtt", "eclipsemosquitto"),
        ("mysql", "mysql"),
        ("n8n", "n8n"),
        ("nextcloud", "nextcloud"),
        ("nginx", "nginx"),
        ("nginxproxymanager", "nginxproxymanager"),
        ("nodedotjs", "nodedotjs"),
        ("nodeexporter", "prometheus"),
        ("nodejs", "nodedotjs"),
        ("npmapp", "nginxproxymanager"),
        ("ntfy", "ntfy"),
        ("ollama", "ollama"),
        ("onlyoffice", "onlyoffice"),
        ("openai", "openai"),
        ("paperless", "paperlessngx"),
        ("paperlessngx", "paperlessngx"),
        ("pihole", "pihole"),
        ("plex", "plex"),
        ("portainer", "portainer"),
        ("postgres", "postgresql"),
        ("postgresql", "postgresql"),
        ("prometheus", "prometheus"),
        ("promtail", "grafana"),
        ("python", "python"),
        ("rabbitmq", "rabbitmq"),
        ("redis", "redis"),
        ("searxng", "searxng"),
        ("synapse", "matrix"),
        ("syncthing", "syncthing"),
        ("tailscale", "tailscale"),
        ("traefik", "traefikproxy"),
        ("traefikproxy", "traefikproxy"),
        ("ubuntu", "ubuntu"),
        ("uptimekuma", "uptimekuma"),
        ("valkey", "redis"),
        ("vaultwarden", "vaultwarden"),
        ("vectorim", "element"),
        ("watchtower", "watchtower"),
        ("wireguard", "wireguard"),
    ]

    static let aliases: [String: String] = Dictionary(aliasList, uniquingKeysWith: { first, _ in first })

    /// The brand for the first of `texts` (label, container name, image …)
    /// that names one, or nil.
    static func slug(for texts: [String]) -> String? {
        for raw in texts where !raw.isEmpty {
            let text = raw.lowercased()
            var imageBase = ""
            if text.contains("/") || text.contains(":") {
                let last = text.components(separatedBy: "/").last ?? ""
                imageBase = last.components(separatedBy: ":").first ?? ""
            }
            for candidate in [text, imageBase] where !candidate.isEmpty {
                if let slug = aliases[normalized(candidate)] { return slug }
            }
            for part in text.split(whereSeparator: { !isWordCharacter($0) }) where part.count >= 3 {
                if let slug = aliases[String(part)] { return slug }
            }
            let squashed = normalized(text)
            for (alias, slug) in aliasList where alias.count >= 4 && squashed.contains(alias) {
                return slug
            }
        }
        return nil
    }

    private static func normalized(_ text: String) -> String {
        String(text.filter(isWordCharacter))
    }

    /// [a-z0-9] of the lower-cased text, exactly what the web client keeps.
    private static func isWordCharacter(_ character: Character) -> Bool {
        guard let scalar = character.unicodeScalars.first, character.unicodeScalars.count == 1 else { return false }
        return ("a"..."z").contains(scalar) || ("0"..."9").contains(scalar)
    }
}
