#!/usr/bin/env python3
"""Generate the app's brand marks from the web client's icon set.

web/icons.js is the single source: the Simple Icons brand marks (CC0) the
web app draws on its service tiles, their brand colours, and the aliases that
map container names and images to a brand. This writes

  App/Resources/Assets.xcassets/Brands/brand-<slug>.imageset   one template SVG each
  App/Core/Brands.swift                                         colours, aliases, matching

so both clients show the same mark for the same service. Re-run after
web/icons.js changes; tests/test_brand_assets.py fails while they differ.

    python3 tools/gen-brands.py
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parent / "App"
WEB = HERE.parent.parent / "web"
CATALOG = APP / "Resources" / "Assets.xcassets" / "Brands"
SWIFT = APP / "Core" / "Brands.swift"


def parse_icons(js: str) -> tuple[dict[str, tuple[str, str]], list[tuple[str, str]]]:
    brands_src = re.search(r"const BRAND_ICONS = \{(.*?)\n\};", js, re.S).group(1)
    brands = {slug: (hex_.upper(), path) for slug, hex_, path in
              re.findall(r'"([a-z0-9]+)": \[\s*"([0-9A-Fa-f]{6})",\s*"([^"]+)"\s*\]', brands_src)}
    aliases_src = re.search(r"const BRAND_ALIASES = \{(.*?)\n\};", js, re.S).group(1)
    aliases = re.findall(r'"([a-z0-9]+)"\s*:\s*"([a-z0-9]+)"', aliases_src)
    return brands, aliases


def imageset(name: str, svg: str) -> None:
    folder = CATALOG / f"{name}.imageset"
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f"{name}.svg").write_text(svg, encoding="utf-8")
    (folder / "Contents.json").write_text(json.dumps({
        "images": [{"filename": f"{name}.svg", "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1},
        "properties": {"preserves-vector-representation": True,
                       "template-rendering-intent": "template"},
    }, indent=2) + "\n", encoding="utf-8")


def swift_source(brands: dict[str, tuple[str, str]], aliases: list[tuple[str, str]]) -> str:
    colors = "\n".join(f'        "{slug}": 0x{hex_},' for slug, (hex_, _) in sorted(brands.items()))
    pairs = "\n".join(f'        ("{alias}", "{slug}"),' for alias, slug in aliases)
    return f'''// Generated by tools/gen-brands.py from web/icons.js — do not edit by hand.
// Brand marks: Simple Icons (https://simpleicons.org, CC0-1.0). They identify
// third-party services; all trademarks belong to their respective owners.
import Foundation

/// Which brand a service is, by the same rules as the web client's
/// `brandSlug()`, so a container shows the same mark in both.
enum Brands {{
    /// slug → brand colour. The mark itself is the asset `brand-<slug>`.
    static let colors: [String: UInt32] = [
{colors}
    ]

    /// alias → slug, in the web client's order: the substring pass takes the
    /// first alias that fits, so the order is part of the behaviour.
    static let aliasList: [(String, String)] = [
{pairs}
    ]

    static let aliases: [String: String] = Dictionary(aliasList, uniquingKeysWith: {{ first, _ in first }})

    /// The brand for the first of `texts` (label, container name, image …)
    /// that names one, or nil.
    static func slug(for texts: [String]) -> String? {{
        for raw in texts where !raw.isEmpty {{
            let text = raw.lowercased()
            var imageBase = ""
            if text.contains("/") || text.contains(":") {{
                let last = text.components(separatedBy: "/").last ?? ""
                imageBase = last.components(separatedBy: ":").first ?? ""
            }}
            for candidate in [text, imageBase] where !candidate.isEmpty {{
                if let slug = aliases[normalized(candidate)] {{ return slug }}
            }}
            for part in text.split(whereSeparator: {{ !isWordCharacter($0) }}) where part.count >= 3 {{
                if let slug = aliases[String(part)] {{ return slug }}
            }}
            let squashed = normalized(text)
            for (alias, slug) in aliasList where alias.count >= 4 && squashed.contains(alias) {{
                return slug
            }}
        }}
        return nil
    }}

    private static func normalized(_ text: String) -> String {{
        String(text.filter(isWordCharacter))
    }}

    /// [a-z0-9] of the lower-cased text, exactly what the web client keeps.
    private static func isWordCharacter(_ character: Character) -> Bool {{
        guard let scalar = character.unicodeScalars.first, character.unicodeScalars.count == 1 else {{ return false }}
        return ("a"..."z").contains(scalar) || ("0"..."9").contains(scalar)
    }}
}}
'''


def main() -> None:
    brands, aliases = parse_icons((WEB / "icons.js").read_text(encoding="utf-8"))
    if CATALOG.exists():
        shutil.rmtree(CATALOG)
    CATALOG.mkdir(parents=True)
    (CATALOG / "Contents.json").write_text(json.dumps(
        {"info": {"author": "xcode", "version": 1}}, indent=2) + "\n", encoding="utf-8")
    for slug, (_, path) in brands.items():
        imageset(f"brand-{slug}", '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" '
                                  f'viewBox="0 0 24 24"><path d="{path}"/></svg>\n')
    # PocketADM itself (the app's own container) shows the app icon
    icon = CATALOG / "pocketadm-mark.imageset"
    icon.mkdir()
    shutil.copy(APP / "Resources" / "Assets.xcassets" / "AppIcon.appiconset" / "icon-1024.png",
                icon / "pocketadm-mark.png")
    (icon / "Contents.json").write_text(json.dumps({
        "images": [{"filename": "pocketadm-mark.png", "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1},
    }, indent=2) + "\n", encoding="utf-8")
    SWIFT.write_text(swift_source(brands, aliases), encoding="utf-8")
    print(f"✓ {len(brands)} brand marks + the PocketADM icon, {len(aliases)} aliases")


if __name__ == "__main__":
    main()
